//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PranzoDoodle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carpooltoolEntities : DbContext
    {
        public carpooltoolEntities()
            : base("name=carpooltoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PranzoOptions> PranzoOptions { get; set; }
        public virtual DbSet<PranzoUsers> PranzoUsers { get; set; }
        public virtual DbSet<PranzoSettings> PranzoSettings { get; set; }
    }
}
