//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PranzoDoodle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PranzoUsers
    {
        public int id { get; set; }
        public string nome { get; set; }
        public int preferenza { get; set; }
    
        public virtual PranzoOptions PranzoOptions { get; set; }
    }
}
