//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PranzoDoodle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PranzoOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PranzoOptions()
        {
            this.PranzoUsers = new HashSet<PranzoUsers>();
        }
    
        public int id { get; set; }
        public string descrizione { get; set; }
        public short defaultOption { get; set; }
        public string nome { get; set; }
        public string telefono { get; set; }
        public string menuUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PranzoUsers> PranzoUsers { get; set; }
    }
}
